### ISSUE TITLE
Support passing arguments to the binary

### ISSUE THREAD

**Issue by lu-zero** [jfrimmel/cargo-valgrind#27] opened 2019-11-22 19:34 UTC
`cargo valgrind -- --args` does not work as it does for `cargo run`.

**Comment by jfrimmel** [comment] 2019-11-24 12:57
Duplicate of #19. I've already started working on this topic, but discontinued, since I didn't need it for myself. Since you request this feature, I hope to be able to support this soon.

**Closed** 2019-11-30 10:24 UTC

**Comment by jfrimmel** [comment] 2019-11-30 10:26
@lu-zero Please try, if it works for you now. If not, feel free to reopen this issue.

**Comment by lu-zero** [comment] 2019-12-16 09:07
It does work well, thank you a lot!
