### ISSUE TITLE
how to interpret the output ?

### ISSUE THREAD

**Issue by cometta** [jfrimmel/cargo-valgrind#79] opened 2024-09-15 00:50 UTC
when i ran the unit-test, i get output like below

```
Error leaked 6.5 kiB in 16 blocks
        Info at malloc
             at alloc::alloc::alloc (alloc.rs:100)
             at alloc::alloc::Global::alloc_impl (alloc.rs:183)
             at <alloc::alloc::Global as core::alloc::Allocator>::allocate (alloc.rs:243)
             at do_alloc<alloc::alloc::Global> (alloc.rs:15)
             at hashbrown::raw::RawTableInner::new_uninitialized (mod.rs:1750)
             at hashbrown::raw::RawTableInner::fallible_with_capacity (mod.rs:1788)
             at prepare_resize<alloc::alloc::Global> (mod.rs:2864)
             at resize_inner<alloc::alloc::Global> (mod.rs:3060)
             at reserve_rehash_inner<alloc::alloc::Global> (mod.rs:2950)
             at hashbrown::raw::RawTable<T,A>::reserve_rehash (mod.rs:1231)
             at hashbrown::raw::RawTable<T,A>::reserve (mod.rs:1179)
             at hashbrown::raw::RawTable<T,A>::find_or_find_insert_slot (mod.rs:1413)
             at hashbrown::map::HashMap<K,V,S,A>::insert (map.rs:1754)
             at std::collections::hash::map::HashMap<K,V,S>::insert (map.rs:1106)
             at regex_automata::hybrid::dfa::Lazy::add_state (dfa.rs:2309)
     Summary Leaked 17.0 kiB total
error: test failed, to rerun pass `--lib`

```

Can enlighten me, how to interpret the output and find out which line of my rust code has the leak ?

**Comment by jfrimmel** [comment] 2024-09-17 10:57
Hi, 
thank you for using this tool. Keep in mind, that the tool is a front-end for good old valgrind, so any information on valgrind itself is suitable for this tool as well. If you need the generated stack trace, you see, that an allocation is performed via the Rust standard library (`do_alloc<alloc::alloc::Global> (alloc.rs:15)` and above), which is caused by a hasmap (the `hashbrown`-stuff, which is the implementation of hash-maps in the standard library), ultimately caused by the DFA-construction in `regex_automata`. So, in short: it looks like there is a memory leak in the `regex_automata`-crate. Note, that valgrind is not 100% accurate all the time and sometimes programs deliberately leak memory for various reasons, thus this _could_ simply be ignored (YMMV).

As there is no immediate problem with `cargo valgrind` itself, I'll go ahead and close this issue. Be free to ask further questions even on the closed issue (or simply re-open it).

**Closed by jfrimmel** 2024-09-17 10:57 UTC
